services:
  web:
    build: .
    container_name: web
    command: python app.py
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
  
  worker:
    build: .
    container_name: worker
    command: rq worker -c settings
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

